<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>jxs Demonistration</title>
<link rel="stylesheet" href="style.css" type="text/css" />
<script type="text/javascript" src="jxs.js"></script>
<script type="text/javascript" src="../xml_parser/xml2array.js"></script>
<script type="text/javascript" src="../../js/debug.js"></script>
<script type="text/javascript">
/* <![CDATA[ */
// Hi, 
// I appreciate the fact that your were curious enought to look under the hood of this page.
// But, don't be mislead by the code given here. I made it somewhat complicated to reduce
// the amount of coding needed for this demo.
// Use the codes generated by this page and shown in the 'Code' textarea.
var data_format = 'json';

function $(id){return document.getElementById(id);}
function $F(id){return $(id).value;}
function makeCall() {
    data_format = $F("returns");
    var method = $F("methods");
    var url = $F("url");

    if(data_format == 'json') url += "&format=json";
    if(data_format == 'xml')  url += "&format=xml";

    load(url,data_format,method);

    return false;
}
function customHandler() {
    $("txt").value = "";
    $("code").value = "jx.load(url, false, 'text', 'get', {'handler': function(http) {\n"
        + " /* ... Do what you want with the 'http' variable ... */\n}});";

    jx.load("data.php?fetch=1",false,'text', 'post', {"handler":function(http) {
        $("txt").value += "Ready State : " + http.readyState + "\n";
        
        if(http.readyState == 4) {
            $("txt").value += "\nStatus : " + http.status + "\n\n";
            $("txt").value += "Response...\n" + http.responseText;
        }
    }});
}
function load(url,data_format,method,e) {
    window.data_format = data_format;
    var code = "";
    if($('use_load').checked) {
        //Show the code in the textarea
        code = "jx.load('"+url+"',function(data){\n"
            + " /* \n   ... do what you want with 'data' variable ... \n    */\n    },'"
            + data_format+"','"+method+"');";
        $("loading").style.display='block';
        jx.load(url,handler,data_format,method);

    } else if($('use_bind').checked) {
        //Show the code in the textarea
        code = "jx.bind({\n "
            +"\"url\":'"+url+"',\n  "
            +'"onSuccess":handler,\n    '
            +'"onError":function(status){alert("Something when wrong. Error : "+status)},\n '
            +'"format":"'+data_format+'",\n '
            +'"method":"'+method+'",\n  '
            +'"loading":"loading"\n'
        +"});";
    
        jx.bind({
            "url":url,
            "onSuccess":handler,
            "onError":function(status){alert("Something when wrong. Error : "+status);},
            "format":data_format,
            "method":method,
            "loading":"loading"
        });
    
    }

    $("code").value = code;
    
    if(!e) var e = window.event;
    if(!e) return false;
    if(e.stopPropogation) {
        e.stopPropagation();
        e.preventDefault();
    }
    return false;
}

//The jx calles this function when the requested url is called. This function 
//      is the second argument of the jx.load function.
function handler(data) {
    var txt;
    var t = $("txt");
    
    $("loading").style.display='none';

    if(data_format == 'json') {
        txt = dump(data);
        t.value = "Parsed Text\n===========\n" + txt;
    } else if(data_format == 'xml') {
        txt = dump(xml2array(data));
        t.value = "Parsed Text\n===========\n" + txt;

    } else {
        t.value = data;
    }
}

function execCode() {
    var code = $F('code');
    $('txt').value="";
    
    eval(code);
}
/* ]]> */
</script>
</head>
<body>
<h1><a href="index.php">jxs</a> Demonistration</h1>

<h2>Tests</h2>

<div id="tests">
<div id="test-returns" class="test-box">
<h3>Return Types</h3>
<ul>
<li><a href="data.php?fetch=true&amp;dummy=text&amp;lora=ipsum" onclick="return load(this.href,'text','get',event);">Text</a></li>
<li><a href="data.php?fetch=true&amp;dummy=text&amp;lora=ipsum&amp;format=json" onclick="return load(this.href,'json','get',event);">JSON</a></li>
<li><a href="data.php?fetch=true&amp;dummy=text&amp;lora=ipsum&amp;format=xml"  onclick="return load(this.href,'xml','get',event);">XML</a></li>
</ul>
</div>

<div id="test-methods" class="test-box">
<h3>Methods</h3>
<ul>
<li><a href="data.php?fetch=true&amp;dummy=text&amp;lora=ipsum" onclick="return load(this.href,'text','get',event);">GET</a></li>
<li><a href="data.php?fetch=true&amp;dummy=text&amp;lora=ipsum" onclick="return load(this.href,'text','post',event);">POST</a></li>
</ul>
</div>

<div id="custom-test" class="test-box">
<h3>Custom</h3>

<form onsubmit="return makeCall();" name="custom" action="data.php">
<label for="url">URL + Parameter</label>
<input type="text" name="url" id="url" value="data.php?fetch=true&amp;num=42&amp;name=marvin" /><br />

<label for="methods">Method</label>
<select name="methods" id="methods">
<option value="post">POST</option>
<option value="get">GET</option>
</select><br />

<label for="returns">Return Type</label>
<select name="returns" id="returns">
<option value="text">Text</option>
<option value="json">JSON</option>
<option value="xml">XML</option>
</select><br />

<input type="button" name="action" value="Call" onclick="makeCall();" /><br /><br />
<input type="button" name="custom-handler" value="Use Custom Handler" onclick="customHandler();" />
</form>
</div>

<div id="test-functions" class="test-box">
<h3>Use Function</h3>
<input type="radio" name="use_function" id="use_load" checked="checked" /> <label for="use_load">load()</label><br />
<input type="radio" name="use_function" id="use_bind" /> <label for="use_bind">bind()</label><br />
NOTE:This option only works with the 'Call' Button.

</div>

</div>

<br />
<div id="loading-holder">
<div id="loading"><img src="../../images/display/loading1.gif" alt="Loading..." /> Loading...</div>
</div>
<hr />

<div>

<div id="results-area">
<h2>Result</h2>

<form method="post" onsubmit="return false;" name="result_form" id="result_form" action="data.php">
<textarea id="txt">
</textarea>
</form>
</div>

<div id="code-area">
<h2>Code</h2>
<form method="post" onsubmit="return false;" name="code_form" id="code_form" action="data.php">
<input type="button" value="Execute Code" onclick="execCode()" />
<textarea id="code">
</textarea>
</form>
</div>
</div>

</body>
</html>
